// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'page': string;
  'title': string;
  'whiteLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
