/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const page: string;
declare const card: string;
declare const title: string;
declare const whiteLabel: string;

export {
	page,
	card,
	title,
	whiteLabel
};

declare const __default_export__: {
	page: typeof page;
	card: typeof card;
	title: typeof title;
	whiteLabel: typeof whiteLabel;
};
export default __default_export__;
