// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'layoutRoot': string;
  'logo': string;
  'userDropdown': string;
}
export const cssExports: CssExports;
export default cssExports;
