/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const layoutRoot: string;
declare const logo: string;
declare const header: string;
declare const userDropdown: string;

export {
	layoutRoot,
	logo,
	header,
	userDropdown
};

declare const __default_export__: {
	layoutRoot: typeof layoutRoot;
	logo: typeof logo;
	header: typeof header;
	userDropdown: typeof userDropdown;
};
export default __default_export__;
